name: "oauth2"
mode: "dev"
port: 8000
version: "0.0.1"
machine_id: 1

sentry:
  dsn: "https://xxxxxxxxxxxxxxxxxx@sentry.io/1"

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "123456"
  db: "oauth2"
  max_idle_conns: 10
  max_open_conns: 50

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 50

wechat:
  app_id: "xxxxxxxxxxxxxxxxxx"
  app_secret: "xxxxxxxxxxxxxxxxxx"

qiniu:
  access_key: "xxxxxxxxxxxxxxxxxx"
  secret_key: "xxxxxxxxxxxxxxxxxx"

secret:
  oauth2: "oauth2"
  access_token: "access_token"
  refresh_token: "refresh_token"
