// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login/oauth2": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "通过签名获取token",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/network.GenLoginTokenByOauth2PostParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/network.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/network.HTTPErrResponse"
                        }
                    },
                    "422": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/network.HTTPErrResponse"
                        }
                    },
                    "500": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/network.HTTPErrResponse"
                        }
                    }
                }
            }
        },
        "/oauth2/wechat/required/subscribe": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Oauth2"
                ],
                "summary": "微信登录接口",
                "parameters": [
                    {
                        "type": "string",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "重定向的uri",
                        "name": "redirect",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "university",
                        "description": "重定向：university",
                        "name": "service",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "state",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/network.HTTPErrResponse"
                        }
                    },
                    "422": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/network.HTTPErrResponse"
                        }
                    },
                    "500": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/network.HTTPErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "network.GenLoginTokenByOauth2PostParam": {
            "type": "object",
            "required": [
                "sign"
            ],
            "properties": {
                "sign": {
                    "description": "登录签名",
                    "type": "string"
                }
            }
        },
        "network.HTTPErrResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "err_code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "now_ts": {
                    "type": "integer"
                }
            }
        },
        "network.LoginResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "$ref": "#/definitions/network.LoginToken"
                },
                "err_code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "now_ts": {
                    "type": "integer"
                }
            }
        },
        "network.LoginToken": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Oauth2",
	Description: "Oauth2后端API接口文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
